version: '3.8'

services:
  backend: 
    # For pushing into Docker Hub 
    image: rohanv7/dev-booklio-backend:latest

    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-booklio-backend 
    ports:
      - "3001:3000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: dev-redis
    ports:
      - "6380:6379"
