const swaggerAutogen = require('swagger-autogen')();
const fs = require('fs');
const path = require('path');

// Swagger Autogen Documentation Configuration
const doc = {
    info: {
        title: '📚 Booklio API',
        description: `
Welcome to the **Booklio API**!  
Booklio empowers buyers, sellers, and book enthusiasts to connect seamlessly in one platform.  

✨ **API Overview**:  
- 📖 **Add/Remove Books**: Easily manage your book inventory as a seller.  
- 🛍️ **Browse Books by Genre**: Discover a wide range of genres to suit your taste.  
- 🤝 **Seller & Stock Management**: Keep track of stock levels and find sellers for specific books.  
- 🔍 **Advanced Book Search**: Filter by genre, ISBN, or seller to find exactly what you need.  

This API is designed for developers building applications that connect buyers and sellers in the Booklio ecosystem. From browsing books to managing sellers, Booklio provides all the endpoints you'll need.  
Let's make the world of books more accessible, one API call at a time! 🚀
        `,
    }
};



const inputSwaggerFile = './swagger/swagger-name-input.json'; // Intermediate JSON file (generated by swagger-autogen)
const outputSwaggerFile = './swagger/swagger-output.json'; // Final JSON file with dynamically added tags
const routes = ['../routes/*.js', '../routes/management/*.js', '../routes/management/admin/*.js']; // Route definitions

/**
 * Generate Swagger JSON file with tags dynamically based on the first segment in the route path.
 * @param {string} inputFilePath - Path to the input Swagger JSON file.
 * @param {string} outputFilePath - Path to the output Swagger JSON file.
 */
const generateSwaggerWithTags = (inputFilePath, outputFilePath) => {
    try {
        // Read and parse the input JSON file
        const rawData = fs.readFileSync(inputFilePath, 'utf8');
        const swaggerDoc = JSON.parse(rawData);

        const tagsMap = new Map();

        // Iterate over the paths and group them by tags based on the first segment in the route
        Object.keys(swaggerDoc.paths).forEach((route) => {
            const segments = route.split('/');
            if (segments.length > 1 && segments[1]) {
                const prefix = segments[1]; // Extract the first word after the initial slash
                const tagName = `${prefix.charAt(0).toUpperCase() + prefix.slice(1)}`; // Capitalize the prefix

                // Add tag to tagsMap if not already present
                if (!tagsMap.has(tagName)) {
                    tagsMap.set(tagName, {
                        name: tagName,
                        description: `Endpoints for ${prefix}`
                    });
                }

                // Update the route in paths to include the tag
                const methods = swaggerDoc.paths[route];
                Object.keys(methods).forEach((method) => {
                    if (!methods[method].tags) {
                        methods[method].tags = [];
                    }
                    if (!methods[method].tags.includes(tagName)) {
                        methods[method].tags.push(tagName);
                    }
                });
            }
        });

        // Add the tags to the Swagger JSON
        swaggerDoc.tags = Array.from(tagsMap.values());

        // Write the updated JSON to the output file
        fs.writeFileSync(outputFilePath, JSON.stringify(swaggerDoc, null, 4), 'utf8');
        console.log(`Updated Swagger JSON file generated at: ${outputFilePath}`);
    } catch (error) {
        console.error('Error processing Swagger JSON:', error.message);
    }
};

// Generate the initial Swagger file using swagger-autogen
const generateSwaggerFile = async () => {
    try {
        console.log('Generating initial Swagger JSON...');
        await swaggerAutogen(inputSwaggerFile, routes, doc);
        console.log(`Swagger JSON file created at: ${inputSwaggerFile}`);

        // Once the initial file is created, dynamically add tags
        generateSwaggerWithTags(inputSwaggerFile, outputSwaggerFile);
    } catch (error) {
        console.error('Error generating Swagger JSON:', error.message);
    }
};

// Execute the process
generateSwaggerFile();
